### ISSUE TITLE
Trying to verify LineageOS Recovery results in an error

### ISSUE THREAD

**Issue by ghost** [gmrt/update_verifier#2]
user@fdvlm:~/Downloads/update_verifier$ python3 update_verifier.py lineageos_pubkey /media/sf_Downloads/lineage-18.1-20210401-recovery-ether.img
Traceback (most recent call last):
  File "update_verifier.py", line 130, in <module>
    main()
  File "update_verifier.py", line 118, in main
    signed_file.verify(args.public_key)
  File "update_verifier.py", line 94, in verify
    self.check_valid()
  File "update_verifier.py", line 77, in check_valid
    assert self.footer[2] == 255 and self.footer[3] == 255, (
AssertionError: Footer has wrong magic

**Comment by gmrt** [comment]
I think you are using https://github.com/LineageOS/update_verifier or some other fork, there's no python code in this repo.
